export const laLigaTeams = [
  "Alavés",
  "Athletic Club",
  "Atlético de Madrid",
  "Barcelona",
  "Real Betis",
  "Celta de Vigo",
  "Espanyol",
  "Getafe",
  "Girona",
  "Las Palmas",
  "Leganés",
  "Mallorca",
  "Osasuna",
  "Rayo Vallecano",
  "Real Madrid",
  "Real Sociedad",
  "Sevilla",
  "Valencia",
  "Valladolid",
  "Villarreal",
];
